### PR TITLE
Pharmacy Tkinter Frontend

### PR DESCRIPTION
**Pull request by FieryDeveloper**
Works perfectly in pycharm. PIL Library not there for me in vscode

### CODE REVIEW

**Comment by khawajaazfar** [comment]
Great I'm merging it , Keep contributing. Was it's your semester project?

**Comment by FieryDeveloper** [comment]
Actually I was doing it as a side project for fun.
However sir I had one question
These commits if they are accepted..
This repository has to be accepted too?

**Comment by khawajaazfar** [comment]
Yes, there are certain rules for the repositories to follow to be consider in hacktoberfest and this repository are following thhem and people who as contributed in it their pull request is accepted by github.

**Comment by FieryDeveloper** [comment]
Great.
Thanks for the info sir

**Pull request merged**
